CREATE TABLE challenge_record
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stem_id      BIGINT                                  NOT NULL,
    attempted_at TIMESTAMP WITHOUT TIME ZONE,
    result       VARCHAR(64)                             NOT NULL,
    note         VARCHAR(255),
    CONSTRAINT pk_challenge_record PRIMARY KEY (id)
);

CREATE TABLE challenge_statistics
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stem_id       BIGINT                                  NOT NULL,
    state         VARCHAR(255)                            NOT NULL,
    count         BIGINT,
    last_modified TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_challenge_statistics PRIMARY KEY (id)
);

CREATE TABLE stem
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    term          VARCHAR(255)                            NOT NULL,
    ipa           VARCHAR(64),
    note          VARCHAR(255),
    created       TIMESTAMP WITHOUT TIME ZONE,
    last_modified TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_stem PRIMARY KEY (id)
);

CREATE TABLE term_relation
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id    BIGINT                                  NOT NULL,
    target_id    BIGINT                                  NOT NULL,
    relationship VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_term_relation PRIMARY KEY (id)
);

CREATE TABLE word
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stem_id        BIGINT                                  NOT NULL,
    part_of_speech VARCHAR(255)                            NOT NULL,
    ipa            VARCHAR(64),
    variants       VARCHAR(255),
    translation    VARCHAR(255)                            NOT NULL,
    explanation    VARCHAR(1024),
    example        VARCHAR(1024),
    created        TIMESTAMP WITHOUT TIME ZONE,
    last_modified  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_word PRIMARY KEY (id)
);

ALTER TABLE stem
    ADD CONSTRAINT uc_stem_term UNIQUE (term);

ALTER TABLE word
    ADD CONSTRAINT uq_stem_pos UNIQUE (stem_id, part_of_speech);

ALTER TABLE challenge_statistics
    ADD CONSTRAINT uq_stem_state UNIQUE (stem_id, state);

ALTER TABLE term_relation
    ADD CONSTRAINT uq_term_id UNIQUE (source_id, target_id);

ALTER TABLE word
    ADD CONSTRAINT FK_WORD_ON_STEM FOREIGN KEY (stem_id) REFERENCES stem (id);