
spring:
  mvc:
    problemdetails:
      enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    generate-unique-name: false
########################################################################################################################

app:
  stem-selection-size: 20