
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wordsmith
  jpa:
    properties:
      hibernate:
        format_sql: false
    show-sql: true
########################################################################################################################

app:
  stem-selection-size: 20