
spring:
  mvc:
    problemdetails:
      enabled: true
  jpa:
    open-in-view: false
  datasource:
    generate-unique-name: false
########################################################################################################################

app:
  stem-selection-size: 20