
spring:
  mvc:
    problemdetails:
      enabled: true
  datasource:
    generate-unique-name: false
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  flyway:
    locations: classpath:db/migration/{vendor}
    baseline-on-migrate: true
########################################################################################################################

app:
  stem-selection-size: 20